# Generated by Django 3.0.1 on 2020-01-13 22:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_auto_20200112_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedroom',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
