# Generated by Django 3.1.1 on 2020-10-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_auto_20201007_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroom',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(upload_to='team/'),
        ),
    ]
